"""empty message

Revision ID: 8bd41db8e692
Revises: 03d76e7dcb93
Create Date: 2023-05-10 03:07:50.325935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd41db8e692'
down_revision = '03d76e7dcb93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_name_key', type_='unique')
        batch_op.drop_constraint('product_price_key', type_='unique')
        batch_op.drop_constraint('product_product_img_key', type_='unique')
        batch_op.drop_constraint('product_status_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_status_key', ['status'])
        batch_op.create_unique_constraint('product_product_img_key', ['product_img'])
        batch_op.create_unique_constraint('product_price_key', ['price'])
        batch_op.create_unique_constraint('product_name_key', ['name'])

    # ### end Alembic commands ###
